"use client";

import { useCallback, useEffect, useState } from "react";
import { Sparkles, RefreshCw, Lightbulb, AlertTriangle } from "lucide-react";

import { getInsights, type CareerInsights, type Recommendation } from "@/lib/career-insights-api";
import { getNodes, type KnowledgeNodeItem } from "@/lib/career-brain-api";
import { EvidenceChip } from "@/components/evidence-chip";
import { EmptyState } from "@/components/empty-state";
import { Skeleton } from "@/components/ui/skeleton";

const EMPTY_MESSAGE = "Upload and extract a document to generate career insights.";

export default function InsightsPage() {
  const [insights, setInsights] = useState<CareerInsights | null>(null);
  const [highlightNodes, setHighlightNodes] = useState<Map<string, KnowledgeNodeItem>>(new Map());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    Promise.all([
      getInsights(),
      getNodes({ entityType: "PROJECT" }),
      getNodes({ entityType: "CERTIFICATE" }),
    ])
      .then(([insightsData, projects, certs]) => {
        setInsights(insightsData);
        const byName = new Map<string, KnowledgeNodeItem>();
        for (const node of [...projects, ...certs]) byName.set(node.name, node);
        setHighlightNodes(byName);
      })
      .catch((err) => setError(err instanceof Error ? err.message : "Failed to generate insights."))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  if (loading) {
    return (
      <main className="px-6 py-10 sm:px-10">
        <div className="mx-auto max-w-4xl space-y-4">
          <Skeleton className="h-9 w-64" />
          <Skeleton className="h-32 w-full" />
          <Skeleton className="h-32 w-full" />
          <Skeleton className="h-40 w-full" />
        </div>
      </main>
    );
  }

  if (error) {
    return (
      <main className="px-6 py-10 sm:px-10">
        <div className="mx-auto max-w-4xl">
          <EmptyState
            icon={AlertTriangle}
            title="Couldn't generate insights"
            description={error}
            action={<RetryButton onClick={load} />}
          />
        </div>
      </main>
    );
  }

  if (!insights || insights.resume_summary === EMPTY_MESSAGE) {
    return (
      <main className="px-6 py-10 sm:px-10">
        <div className="mx-auto max-w-4xl">
          <EmptyState
            icon={Sparkles}
            title="No insights yet"
            description={EMPTY_MESSAGE}
          />
        </div>
      </main>
    );
  }

  return (
    <main className="px-6 py-10 sm:px-10">
      <div className="mx-auto max-w-4xl">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-display text-3xl font-semibold text-foreground">Career Intelligence</h1>
            <p className="mt-1.5 text-sm text-muted">
              Generated by reasoning only over your verified Career Brain data — never raw documents.
            </p>
          </div>
          <RetryButton onClick={load} label="Regenerate" />
        </div>

        <Section title="Professional summary">
          <p className="text-sm leading-relaxed text-foreground">{insights.resume_summary}</p>
        </Section>

        {insights.experience_summary && (
          <Section title="Experience summary">
            <p className="text-sm leading-relaxed text-foreground">{insights.experience_summary}</p>
          </Section>
        )}

        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <Section title="Top strengths" compact>
            <ChipList items={insights.top_strengths} tone="accent" />
          </Section>
          <Section title="Core skills" compact>
            <ChipList items={insights.core_skills} tone="neutral" />
          </Section>
        </div>

        {(insights.project_highlights.length > 0 || insights.certification_highlights.length > 0) && (
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            {insights.project_highlights.length > 0 && (
              <Section title="Project highlights" compact>
                <HighlightList items={insights.project_highlights} nodes={highlightNodes} />
              </Section>
            )}
            {insights.certification_highlights.length > 0 && (
              <Section title="Certification highlights" compact>
                <HighlightList items={insights.certification_highlights} nodes={highlightNodes} />
              </Section>
            )}
          </div>
        )}

        <OpinionBanner />

        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          {insights.weak_skills.length > 0 && (
            <Section title="Skills worth strengthening" compact>
              <RecommendationList items={insights.weak_skills} />
            </Section>
          )}
          {insights.missing_skills.length > 0 && (
            <Section title="Missing skills" compact>
              <RecommendationList items={insights.missing_skills} />
            </Section>
          )}
          {insights.learning_suggestions.length > 0 && (
            <Section title="Learning suggestions" compact>
              <RecommendationList items={insights.learning_suggestions} />
            </Section>
          )}
          {insights.career_recommendations.length > 0 && (
            <Section title="Career recommendations" compact>
              <RecommendationList items={insights.career_recommendations} />
            </Section>
          )}
        </div>
      </div>
    </main>
  );
}

function Section({
  title,
  compact,
  children,
}: {
  title: string;
  compact?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className={`rounded-2xl border border-border bg-surface p-6 ${compact ? "" : "mt-4"}`}>
      <h2 className="font-display text-base font-semibold text-foreground">{title}</h2>
      <div className="mt-3">{children}</div>
    </div>
  );
}

function ChipList({ items, tone }: { items: string[]; tone: "accent" | "neutral" }) {
  if (items.length === 0) return <p className="text-sm text-muted">Nothing extracted yet.</p>;
  return (
    <div className="flex flex-wrap gap-2">
      {items.map((item) => (
        <span
          key={item}
          className={`rounded-full px-3 py-1 text-xs font-medium ${
            tone === "accent" ? "bg-accent-soft text-accent" : "border border-border text-foreground"
          }`}
        >
          {item}
        </span>
      ))}
    </div>
  );
}

function HighlightList({
  items,
  nodes,
}: {
  items: { name: string; reason: string }[];
  nodes: Map<string, KnowledgeNodeItem>;
}) {
  return (
    <ul className="space-y-3">
      {items.map((item) => {
        const node = nodes.get(item.name);
        return (
          <li key={item.name} className="rounded-xl border border-border bg-background p-3">
            <p className="text-sm font-medium text-foreground">{item.name}</p>
            <p className="mt-1 text-xs text-muted">{item.reason}</p>
            {node && (
              <div className="mt-2">
                <EvidenceChip filename={node.filename} quote={node.evidence_quote} />
              </div>
            )}
          </li>
        );
      })}
    </ul>
  );
}

function RecommendationList({ items }: { items: Recommendation[] }) {
  return (
    <ul className="space-y-3">
      {items.map((rec) => (
        <li key={rec.item} className="rounded-xl border border-border bg-background p-3">
          <p className="text-sm font-medium text-foreground">{rec.item}</p>
          <p className="mt-1 flex items-start gap-1.5 text-xs text-muted">
            <Lightbulb size={13} className="mt-0.5 shrink-0 text-accent" />
            {rec.reason}
          </p>
        </li>
      ))}
    </ul>
  );
}

function OpinionBanner() {
  return (
    <div className="mt-4 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">
      <AlertTriangle size={14} className="mt-0.5 shrink-0" />
      <p>
        The sections below are AI-generated opinions about gaps and next steps — not facts pulled from
        your documents. Each one explains its own reasoning; everything above this line is evidence-backed.
      </p>
    </div>
  );
}

function RetryButton({ onClick, label = "Retry" }: { onClick: () => void; label?: string }) {
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-1.5 rounded-full border border-border bg-surface px-3.5 py-1.5 text-sm font-medium text-muted hover:border-accent hover:text-accent"
    >
      <RefreshCw size={14} />
      {label}
    </button>
  );
}
